services:
#    nas_user.example:
#        class: NAS\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    nas_user.registration.form.type:
        class: NAS\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nas_user_registration }



  #  nas_user.registration_listener:
   #     class: NAS\UserBundle\EventListener\RegistrationListener
    #    arguments: []
     #   tags:
      #      - { name: kernel.event_subscriber }